// ESPN 3-harfli (FIFA tarzı) takım kodu → ISO 3166-1 alpha-2 (flagcdn yedeği için).
// Birincil bayrak kaynağı ESPN ülke logosudur; bu harita yalnızca ESPN logosu
// yüklenemezse flagcdn.com'a düşmek için kullanılır.

const FIFA_TO_ISO2: Record<string, string> = {
  TUR: "tr",
  MEX: "mx",
  RSA: "za",
  KOR: "kr",
  CZE: "cz",
  CAN: "ca",
  BIH: "ba",
  USA: "us",
  PAR: "py",
  QAT: "qa",
  SUI: "ch",
  SWI: "ch",
  BRA: "br",
  MAR: "ma",
  SCO: "gb-sct",
  HAI: "ht",
  AUS: "au",
  GER: "de",
  CUW: "cw",
  CUR: "cw",
  NED: "nl",
  HOL: "nl",
  JPN: "jp",
  CIV: "ci",
  ECU: "ec",
  SWE: "se",
  TUN: "tn",
  ESP: "es",
  CPV: "cv",
  ARG: "ar",
  FRA: "fr",
  ENG: "gb-eng",
  POR: "pt",
  BEL: "be",
  CRO: "hr",
  URU: "uy",
  COL: "co",
  SEN: "sn",
  NGA: "ng",
  EGY: "eg",
  ALG: "dz",
  GHA: "gh",
  CMR: "cm",
  IRN: "ir",
  KSA: "sa",
  NOR: "no",
  DEN: "dk",
  POL: "pl",
  AUT: "at",
  ITA: "it",
  NZL: "nz",
  PAN: "pa",
  CRC: "cr",
  JOR: "jo",
  UZB: "uz",
  WAL: "gb-wls",
  NIR: "gb-nir",
  SRB: "rs",
  GRE: "gr",
  UKR: "ua",
  PER: "pe",
  CHI: "cl",
  COD: "cd",
  JAM: "jm",
  HON: "hn",
  SLV: "sv",
  SVN: "si",
  SVK: "sk",
  HUN: "hu",
  ROU: "ro",
  IRL: "ie",
  IRQ: "iq",
  UAE: "ae",
};

export function iso2FromAbbr(abbr?: string): string | undefined {
  if (!abbr) return undefined;
  return FIFA_TO_ISO2[abbr.toUpperCase()];
}

export function flagcdnUrl(abbr?: string): string | undefined {
  const iso = iso2FromAbbr(abbr);
  return iso ? `https://flagcdn.com/w320/${iso}.png` : undefined;
}
